- name: variables from inventory
  hosts: CONTROLLER
  tasks:
    - name: print URL
      ansible.builtin.debug: 
        msg: URL -- {{ URL }} COMPONENT -- {{ COMPONENT }}
  
- name: variables from playbook
  hosts: FRONTEND
  vars:
    PLAY1: frontend.com
  vars_files:
    sample-vars.yaml
  tasks:
    - name: print URL
      ansible.builtin.debug:
        msg:  PLAY1 -- {{ PLAY1 }} PLAY2 -- {{ PLAY2 }}

- name: variables from roles
  hosts: FRONTEND
  roles:
    - variables-sample